{% set name = "shippinglabel" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shippinglabel-{{ version }}.tar.gz
  sha256: baf43a3231e9d57eb73e510340a6a260c2e807bfe0aace0a7c5c99a0278d3574

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=40.6.0
  run:
    - dist-meta >=0.1.2
    - dom-toml >=0.2.2
    - domdf-python-tools >=3.1.0
    - packaging >=20.9
    - python >={{ python_min }}
    - typing-extensions >=3.7.4.3

test:
  imports:
    - shippinglabel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/domdfcoding/shippinglabel
  summary: Utilities for handling packages.
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - shippinglabel/_vendor/trove_classifiers/LICENSE
  doc_url: shippinglabel.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
