{% set name = "shippinglabel" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shippinglabel-{{ version }}.tar.gz
  sha256: 26abe446306d94f3bae8d9c6740b732868f1f982535e0785947e4a74858d1f1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - apeye >=1.0.0
    - dist-meta >=0.1.2
    - dom-toml >=0.2.2
    - domdf-python-tools >=3.1.0
    - packaging >=20.9
    - platformdirs >=2.3.0
    - python >=3.6
    - typing-extensions >=3.7.4.3

test:
  imports:
    - shippinglabel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/shippinglabel
  summary: Utilities for handling packages.
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - shippinglabel/_vendor/trove_classifiers/LICENSE
  doc_url: shippinglabel.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
